title: Philosofriends
author:
  name: Sarah Bruckler
  email: sarahkb4@illinois.edu
description: >- # this means to ignore newlines until "baseurl:"
  A collection of resources and course materials for students in my courses.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.philosofriends.com" # the base hostname & protocol for your site, e.g. http://example.com 

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Socials
twitter_username: 
github_username: