# Site settings
title: Philosofriends
author: Sarah Bruckler
email: sarahkb4@illinois.edu
description: >- # this means to ignore newlines until "baseurl:"
  A collection of resources and course materials for students in my courses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.philosofriends.com" # the base hostname & protocol for your site, e.g. http://example.com 

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-email-protect

# Custom variables
powered_by: Powered by <a href="https://jekyllrb.com/" alt="Jekyll">Jekyll</a> and <a href="https://github.com/KingFelix/emerald" alt="Emerald Theme for Jekyll">Emerald Theme for Jekyll</a>

# Options
custom_header: false
custom_nav_footer: false
reverse: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Socials
twitter_username: 
github_username: